### ISSUE TITLE
Crashes while trying to parse non-ascii characters in old file

### ISSUE THREAD

**Issue by hugbubby** [unix121/i3wm-themer#23]
This is my log:

`
```
[0;34;40m [>]  Located the config file [0m

[0;32;40m [>] [0m Located the json file

[0;34;40m [>]  Replacing the colors in .Xresources [0m

[0;32;40m [>] [0m Located your .Xresources file

[0;32;40m [>] [0m Found the Xresources info in the JSON file

[0;32;40m [>] [0m Replacing line: '*background: #162025' with '*background: #162025'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*foreground: #bfbfbf' with '*foreground: #bfbfbf'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*cursorColor: #bfbfbf' with '*cursorColor: #bfbfbf'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color0: #162025' with '*color0: #162025'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color1: #393843' with '*color1: #393843'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color2: #193a48' with '*color2: #193a48'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color3: #235964' with '*color3: #235964'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color4: #193a48' with '*color4: #193a48'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color5: #2a474a' with '*color5: #2a474a'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color6: #662b37' with '*color6: #662b37'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color7: #bfbfbf' with '*color7: #bfbfbf'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color8: #365a5c' with '*color8: #365a5c'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color9: #662b37' with '*color9: #662b37'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color10: #193a48' with '*color10: #193a48'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color11: #193a48' with '*color11: #193a48'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color12: #75404b' with '*color12: #75404b'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color13: #662b37' with '*color13: #662b37'

[0;32;40m [>] [0m Success!

[0;32;40m [>] [0m Replacing line: '*color14: #083842' with '*color14: #083842'

[0;32;40m [>] [0m Success!

[0;34;40m [>]  Replacing the colors in your i3 configuration file [0m

[0;32;40m [>] [0m Located your i3 configuration file

[0;32;40m [>] [0m Found the i3wm info in the JSON file

Traceback (most recent call last):

  File "i3wm-themer.py", line 51, in <module>

    ri.replace_i3( configuration, jfile)

  File "/home/noone/i3wm-themer/src/replace_i3.py", line 15, in replace_i3

    rl.replace_line( configuration['i3-config'], 'client.background', 'client.background 
'+i3wm['client.background'])

  File "/home/noone/i3wm-themer/src/replace_line.py", line 11, in replace_line
    for line in old_file:

  File "/usr/lib/python-exec/python3.5/../../../lib64/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6809: ordinal not in range(128)

````

The program should be able to replace these without crashing. Might I suggest just invoking sed instead of trying to do this in-house with python replacements?

**Comment by unix121** [comment]
Hello sir,
Thanks for posting this, I will look into it asap.
Any suggestion/fix is always welcome.

**Comment by hugbubby** [comment]
NP, I fixed it by converting my polybar and i3 config files to ASCII instead of Unicode, but I'm left with a bunch of ?'s in my config file.

**Comment by unix121** [comment]
Just in case, are you sure you were executing the script using Python3?

**Comment by hugbubby** [comment]
I wasn't, but I just went back and reinstalled the whole themer using it, and reconfirmed thatI get the same issue.

**Comment by hugbubby** [comment]
On closer inspection, the problem seems to arise as a result of my locale being set to "C" instead of en-US.utf-8. I run gentoo, and an eselect locale set 3 (utf-8) fixed it. A fix would be for people with non-unicode locales.

**Comment by unix121** [comment]
About the python 3 thing, I'm sorry it was not mentioned in the README.md , this has been fixed now. I can always add a check to see if it's set to UTF-8 , so I might do that.

**Comment by amarazzi** [comment]
I can't solve this. How did you do it, hugbubby?

**Comment by hugbubby** [comment]
@amarazzi Read last comment.

**Comment by unix121** [comment]
I am closing this one since it has been resolved a while back. In case it comes up again, please re-open it.
